version: 2
jobs:
  build:
    working_directory: /home/ubuntu/mastodon-ansible
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get update -qq
            apt-get install -y --no-install-recommends virtualenv python-pip python-dev build-essential libffi-dev libssl-dev
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            source env/bin/activate
            ansible-playbook playbook.yml -v --connection=local
