- name: Create database user {{ mastodon_db_user }}
  postgresql_user:
    name: "{{ mastodon_db_user }}"
    password: "{{ mastodon_db_password }}"
    login_host: "{{ mastodon_db_login_host }}"
    login_password: "{{ mastodon_db_login_password }}"
    login_user: "{{ mastodon_db_login_user }}"
    port: "{{ mastodon_db_port }}"
    role_attr_flags: CREATEDB
  when:
    - mastodon_db_login_user is defined
    - mastodon_db_login_host is defined
    - mastodon_db_login_password is defined
    - mastodon_db_port is defined

- name: Create database {{ mastodon_db }}
  postgresql_db:
    name: "{{ mastodon_db }}"
    login_host: "{{ mastodon_db_login_host }}"
    login_password: "{{ mastodon_db_login_password }}"
    login_user: "{{ mastodon_db_login_user }}"
    port: "{{ mastodon_db_port }}"
  when:
    - mastodon_db_login_user is defined
    - mastodon_db_login_host is defined
    - mastodon_db_login_password is defined
    - mastodon_db_port is defined

- name: Create database user {{ mastodon_db_user }}
  postgresql_user:
    name: "{{ mastodon_db_user }}"
    password: "{{ mastodon_db_password }}"
    login_unix_socket: "{{ mastodon_db_login_unix_socket }}"
    role_attr_flags: CREATEDB
  when: mastodon_db_login_unix_socket is defined

- name: Create database {{ mastodon_db }}
  postgresql_db:
    name: "{{ mastodon_db }}"
    login_unix_socket: "{{ mastodon_db_login_unix_socket }}"
  when: mastodon_db_login_unix_socket is defined
